---
- name: Create Temporary Directory
  hosts: all
  become: true
  tasks:
    - name: Create /tmp/dir1 Directory
      ansible.builtin.file:
        path: /tmp/dir1
        state: directory
        mode: '0755'
    - name: /tmp/dir1 Link To /tmp/link_to_dir1
      ansible.builtin.file:
        src: /tmp/dir1
        dest: /tmp/link_to_dir1
        state: link
    - name: Add ansibleAdmin user
      ansible.builtin.user:
        name: ansibleAdmin
        state: present
        shell: /bin/bash
    - name: Change /tmp/dir1 To ansibleAdmin
      ansible.builtin.file:
        path: /tmp/dir1
        state: directory
        owner: ansibleAdmin
        group: ansibleAdmin
        mode: "u=rwx,g=rx,o=rx"  